### ISSUE TITLE
Fix aws tests

### ISSUE THREAD

**Issue by MarleneKress79789** [exasol/sagemaker-extension#71]
Currently the aws tests fail with
` botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the CreateAutoMLJob operation: Could not assume role ***. Please ensure that the role exists and allows principal 'sagemaker.amazonaws.com' to assume the role.`

**Comment by umitbuyuksahin** [comment]
- The problem is that the created role is removed by ci-isolation while the cleanup stack is running. 

- Using different permission policies for the created role such as protected-deny-changing-protected-resource-policy could not overcome this problem.

- [ci-isolation](https://github.com/exasol/ci-isolation-aws) project claims that the cleanup stack deletes all resources in the AWS account except resources prefixed with _protected-_ and _persistent-_.  However, regardless of the prefix of the role name (_protected-_ or _persistent-_), the role is removed by the ci-isolation.

- A ticket is creatd in the  [ci-isolation](https://github.com/exasol/ci-isolation-aws)  about the bug of deleting a protected role: https://github.com/exasol/ci-isolation-aws/issues/19

**Comment by ckunki** [comment]
Blocked by https://github.com/exasol/ci-isolation-aws/issues/19
